apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ls5-jan292026
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./app-of-apps
    repoURL: https://github.com/redhat-appstudio-mjf/ls5-jan292026-gitops.git
    targetRevision: main
  destination:
    namespace: hello
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

